### ISSUE TITLE
pure-menu in side bar using Chrome

### ISSUE THREAD

**Issue by nitmws** [absalomedia/grav-theme-purity#6]
When using Chrome 51.0.2704.106 m on a desktop computer or tablet it shows the "pure-menu" (About / Twitter / Github) in the dark blue side bar. Showing the same page in Firefox 47.0 the menu is in the content section aligned to the right.
And: is there a way to switch off the whole pure-menu?

**Comment by absalomedia** [comment]
Unable to replicate alignment issue between Chrome 51 & Firefox 47 (47 & 47.0.1) in testing.

Will place toggle switch to turn on/off footer menu in next release

**Comment by absalomedia** [comment]
Fixed in 0.5.4 release
