### ISSUE TITLE
ERROR when gulp

### ISSUE THREAD

**Issue by oneseedfruit** [absalomedia/grav-theme-purity#7]
```
D:\xampp\htdocs\grav\user\themes\purity\node_modules\rcloader\index.js:39
        if (err) throw err;
                 ^

Error: ENOENT: no such file or directory, open 'D:\xampp\htdocs\grav\user\themes\purity\scss\pure\.csslintrc'
```

**Comment by absalomedia** [comment]
The core Pure repo used in this template is actually a Git submodule of the theme, so as to reduce overheads. Can you please run:
`git submodule update --init --recursive` inside your purity theme directory? This should then build out the core Pure repo that Gulp references
